daiphu_website/apps/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views


from . import views

app_name = "accounts"
urlpatterns = [
    path("profile", views.ProfileView.as_view(), name="profile"),
    # Django Auth
    path("login",auth_views.LoginView.as_view(template_name="login.html"),name="login"),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
]

daiphu_website/apps/contact/urls.py
from django.urls import path
from .views import contact


app_name="contact"
urlpatterns =[
    path("", contact, name='contact')
]

daiphu_website/urls.py
from django.contrib import admin
from django.urls import path, include


from . import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("daiphu_website.apps.public.urls")),
    path("accounts/", include("daiphu_website.apps.accounts.urls")),
    path("contact/", include("daiphu_website.apps.contact.urls")),
]

daiphu_website/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class UserInterest(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)
    
    def _str_(self):
        return self.name


class UserPersona(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=200)

    def _str_(self):
        return self.name


# Create your models here.
class UserProfile(models.Model):
    # owner
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")

    #settings
    is_full_name_displayed = models.BooleanField(default=True)

    # details
    bio = models.CharField(max_length=500, blank=True, null=True)
    website = models.URLField(max_length=200, blank=True, null=True)
    persona = models.ForeignKey(UserPersona, on_delete=models.SET_NULL, blank=True, null=True)

    interest= models.ManyToManyField(UserInterest, blank=True,)

daiphu_website/apps/contact/models.py
from django.db import models

# Create your models here.

daiphu_website/apps/contact/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(required=True, widget = forms.TextInput(attrs={'class': 'form-control','placeholder':"Name"}))
    email = forms.EmailField(required=True, widget = forms.EmailInput(attrs={'class': 'form-control','placeholder':"Email"}))
    message = forms.CharField(required=True, widget= forms.Textarea(attrs={'class': 'form-control','placeholder':"Message","rows":5}))

daiphu_website/apps/accounts/views.py
from django.template import loader

from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = "accounts/profile.html"

daiphu_website/apps/contact/views.py
import bleach
from django.shortcuts import render
from django.http import HttpResponse, HttpRequest
from django.core.mail import send_mail

from daiphu_website import settings

from .forms import ContactForm
# Create your views here.
def contact(request: HttpRequest) -> HttpResponse:
    if request.method == "GET":
        form = ContactForm() 
    elif request.method=="POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            name = bleach.clean(form.cleaned_data["name"])
            email = bleach.clean(form.cleaned_data["email"])
            message = bleach.clean(form.cleaned_data["message"])
            send_mail(
                f"{name} sent an email", message, email, ["settings.DEFAULT_FROM EMAIL"]
            )
            return render(request, "contact.html",{"form": form, "success": True})
    else:
        raise NotImplementedError
    
    return render(request, "contact.html",{"form": form})

daiphu_website/templates/about.html
{% extends 'base.html' %}

{% block title %} About {% endblock%}

{% block content %}

{% load static%}



<header class="masthead" >
</header>

<section style="margin-top:2rem">
    <div class="container">
        
        
        <div class="row justify-content-center">
            <div class="text-center" >
            
                <h2 class="text-uppercase">Về Đại Phú</h2>
                
            </div>
            <div class="col-lg-8">
                <div class="modal-body" style="display:flex; text-align: center" >
                    <!-- Project details-->
                    
                    <p>
                        Công ty TNHH thương mại Đại Phú được thành lập và chính thức đi vào hoạt động năm 1994 với sứ mệnh tiên phong mang đến cho khách hàng những sản phẩm sơn tĩnh điện và thiết bị ngành sơn chất lượng cao. Trải qua 27 năm không ngừng phát triển và cải tiến trên thị trường, Đại Phú tự hào là một trong những thương hiệu sơn bột uy tín nhất tại Việt Nam hiện nay.
                    
                    
                        Luôn hướng đến chuẩn mực quốc tế trong hoạt động, các sản phẩm của Đại Phú được kiểm soát chặt chẽ từ khâu sản xuất, bảo quản cho đến vận chuyển. Hệ thống cơ sở hạ tầng, máy móc và công nghệ tiên tiến nhất thế giới hoạt động liên tục cung ứng số lượng lớn sản phẩm cho thị trường trong nước và xuất khẩu sang các nước khu vực Đông Nam Á.
                    
                        Với bề dày kinh nghiệm, sản phẩm chất lượng và đội ngũ nhân viên có năng lực, tận tâm, Đại Phú đã, đang và sẽ luôn là sự lựa chọn hàng đầu của các doanh nghiệp, cơ sở kinh doanh và của đông đảo khách hàng cá nhân. 
                    </p>
                    
                </div>
            </div>
        </div>
        
    </div>
</section>
<section style="margin-top:2rem" id="about">
    <div class="container">
        <div class="text-center" >
            <h2 class="section-heading text-uppercase">Lịch Sử Hình Thành</h2>
            <h3 class="section-subheading text-muted">&nbsp</h3>
        </div>
        <ul class="timeline">
            <li>
                <div class="timeline-image"><img class="rounded-circle img-fluid" src="static/theme/assets/img/logo2.png" alt="..." /></div>
                <div class="timeline-panel">
                    <div class="timeline-heading">
                        <h4>1994</h4>
                        <h4 class="subheading">Văn phòng thương mại mang thương hiệu Đại Phú</h4>
                    </div>
                    <div class="timeline-body"><p class="text-muted">Thành lập năm 1994, Đại Phú là đơn vị tiên phong kinh doanh các loại sơn bột tĩnh điện, hóa chất xử lý bề mặt kim loại trước khi sơn và thiết bị phun sơn bột tĩnh điện.</p></div>
                </div>
            </li>
            <li class="timeline-inverted">
                <div class="timeline-image"><img class="rounded-circle img-fluid" src="static/theme/assets/img/gema-logo.jpg" alt="..." /></div>
                <div class="timeline-panel">
                    <div class="timeline-heading">
                        <h4>1995</h4>
                        <h4 class="subheading">Nhà Phân Phối Thiết Bị Cho Gema tại Việt Nam</h4>
                    </div>
                    <div class="timeline-body"><p class="text-muted">Năm 1995, với sự chuyên nghiệp và uy tín trong hoạt động, Đại Phú vinh dự trở thành nhà phân phối độc quyền tại Việt Nam cho hãng thiết bị phun sơn nổi tiếng từ Thụy Sĩ - GEMA. </p></div>
                </div>
            </li>
            <li >
                <div class="timeline-image"><img class="rounded-circle img-fluid" src="static/theme/assets/img/protech-logo2.jpg" alt="..." /></div>
                <div class="timeline-panel">
                    <div class="timeline-heading">
                        <h4>1999</h4>
                        <h4 class="subheading">Đại Phú được uỷ quyền sản xuất bột sơn theo công nghệ của Protech-Oxyplast</h4>
                    </div>
                    <div class="timeline-body"><p class="text-muted">Bằng nỗ lực phát triển và khát vọng mang tới những sản phẩm chất lượng quốc tế, năm 1999, Đại Phú chính thức là thành viên của của thương hiệu sơn đa quốc gia Protech - Oxyplast và tiếp nhận ủy quyền sản xuất bột sơn theo công nghệ của nhà sản xuất này.</p></div>
                </div>
            </li>
            <li class="timeline-inverted">
                <div class="timeline-image"><img class="rounded-circle img-fluid" src="static/theme/assets/img/ngay1.jpg" alt="..." /></div>
                <div class="timeline-panel">
                    <div class="timeline-heading">
                        <h4>2000-2002</h4>
                        <h4 class="subheading">Khánh Thành Nhà Máy</h4>
                    </div>
                    <div class="timeline-body"><p class="text-muted">Giai đoạn 2000 - 2002 đánh dấu bước phát triển lớn mạnh của Đại Phú khi khởi công xây dựng nhà máy sản xuất sơn bột tĩnh điện và các loại hóa chất xử lý bề mặt kim loại trước khi sơn. Nhà máy được đặt tại  D2/1, Đường 1B Khu công nghiệp Vĩnh Lộc, Quận Bình Tân, TP. Hồ Chí Minh,Việt Nam; với toàn bộ hệ thống thiết bị nhập khẩu từ Châu Âu, hiện đại hàng đầu thế giới lúc bấy giờ. Nhờ đó, Đại Phú nhanh chóng trở thành nhà sản xuất sơn bột lớn nhất tại Việt Nam. </p></div>
                </div>
            </li>
            <li class="timeline-inverted">
                <div class="timeline-image align-items-center">
                    <h4>
                        Hãy là                     
                        câu chuyện của
                        chúng tôi!
                    </h4>
                </div>
            </li>
        </ul>
    </div>
</section>



{% endblock %}

daiphu_website/templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %} Profile {% endblock%}

{% block content %}
<h1>
    {{ user.get_full_name}} (@{{user.username}})
</h1>

{% with profile=user.profile %}
    {% if profile %}
        <h2>
            {{ profile.persona|default:""}}
        </h2>
        <div>
            {{ profile.bio|default:""}}
        </div>>
        <div>
            {% with website=profile.website|default:""%
            <a href="{{website}}"}>{{ website }}</a>
            {% endwith%}
        </div> 
        <br/>
        <div>
            Interest:
            {% for interest in profile.interests.all %}
                <span>
                    {{ interest.name }}{% if not forloop.last%}, {% endif%}
                </span>
            {% endfor%}
        </div>
    {% endif %}
{% endwith %}


{% endblock %}

daiphu_website/templates/base.html
{% load static %}


<!-- templates/base.html-->
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>{% block title %} Dai Phu Oxyplast- Powder Coating {% endblock%}</title>

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <link rel="icon" type="image/x-icon" href="../static/theme/assets/img/logo.png" />
        <!-- Bootstrap Icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- SimpleLightbox plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>     
        <link href="{% static 'css/main.css' %}" rel="stylesheet" />
    </head>
    <body>
        {% url 'public:about' as about_url %}
        {% url 'public:index' as index_url %}
        {% url 'contact:contact' as contact_url %}
        {% url 'public:san_pham' as san_pham_url %}
        {% url 'public:he_epoxy' as he_epoxy_url %}
        {% url 'public:he_polyester_epoxy' as he_polyester_epoxy_url %}
        {% url 'public:he_polyester_tgic' as he_polyester_tgic_url %}
        {% url 'public:he_polyester_haa' as he_polyester_haa_url %}
        {% url 'public:he_polyester_urethane' as he_polyester_urethane_url %}
        {% url 'public:thiet_bi' as thiet_bi_url %}
        {% url 'public:equip_auto' as equip_auto_url %}
        {% url 'public:auto_booth' as auto_booth_url %}
        {% url 'public:auto_injector' as auto_injector_url %}
        {% url 'public:enamel_booth' as enamel_booth_url %}
        {% url 'public:multistar' as multistar_url %}
        {% url 'public:optiflex' as optiflex_url %}
        {% url 'public:optigun' as optigun_url %}
        {% url 'public:optispray' as optispray_url %}
        {% url 'public:optistar' as optistar_url %}
        {% url 'public:powder_center' as powder_center_url %}
        {% url 'public:powder_hopper' as powder_hopper_url %}
        {% url 'public:reciprocator' as reciprocator_url %}
        {% url 'public:optimove' as optimove_url %}
        {% url 'public:magic_control' as magic_control_url %}
        {% url 'public:equip_manual' as equip_manual_url%}
        {% url 'public:optiselect' as optiselect_url%}
        {% url 'public:manual_booth' as manual_booth_url%}
        {% url 'public:manual_injector' as manual_injector_url%}
        {% url 'public:manual_optiflex' as manual_optiflex_url%}
        {% url 'public:manual_optispray' as manual_optispray_url%}
        {% url 'public:bot_son' as bot_son_url %}
        {% url 'public:bot_son_trong_nha' as trong_nha_url %}
        {% url 'public:bot_son_ngoai_troi' as ngoai_troi_url %}
        {% include 'navbar.html' %}
        
        
        <main id="main">
            {% block content %}
            
            {% endblock %}
        </main>
        

        
        <div class="row">
            <hr class="divider2">
        </div>
        
        <footer class="footer py-4 ">
            <div class="container">
                <div class="row ">
                    <div class="col-lg-4 text-lg-start " >Copyright &copy; 2010 - CÔNG TY TNHH TM ĐẠI PHÚ- 
                        <br>Thành viên của Protech/ Oxyplast Group 
                    </div>
                    <div class="col-lg-4 my-3 my-lg-0">
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fab fa-instagram"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="https://www.facebook.com/C%C3%B4ng-Ty-TNHH-TM-%C4%90%E1%BA%A1i-Ph%C3%BA-102304405574158" target="_blank"><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="#!"><i class="fas fa-globe"></i></a>
                        <div class="px-5 px-lg-5">
                            <img src="/static/theme/assets/img/protech-logo.gif" height="60px" >
                        </div>
                    </div>
                    <div class="col-lg-4 text-lg-end" >
                        <a class="text-decoration-none me-3 " style="color:#C0BCBC" href="#!">Privacy Policy</a>
                        <a class="text-decoration-none" style="color:#C0BCBC" href="#!">Terms of Use</a>
                    </div>
                    
                </div>
            </div>
            <!-- Messenger Chat Plugin Code -->
    <div id="fb-root"></div>

    <!-- Your Chat Plugin code -->
    <div id="fb-customer-chat" class="fb-customerchat">
    </div>

    <script>
      var chatbox = document.getElementById('fb-customer-chat');
      chatbox.setAttribute("page_id", "102304405574158");
      chatbox.setAttribute("attribution", "biz_inbox");

      window.fbAsyncInit = function() {
        FB.init({
          xfbml            : true,
          version          : 'v12.0'
        });
      };

      (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/vi_VN/sdk/xfbml.customerchat.js';
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    </script>
        </footer>
                
                <!-- Bootstrap core JS-->
                <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
                <!-- SimpleLightbox plugin JS-->
                <script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
                <!-- Core theme JS-->
                <script src="{% static 'theme/js/scripts.js' %}"></script>
               
                <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
                <!-- * *                               SB Forms JS                               * *-->
                <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
                <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
                <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
               
               
                
    </body>

</html>

daiphu_website/templates/bot_son/bot_son.html
{% extends 'base.html' %}

{% load static %}

{% block title %} powder_coating {% endblock%}

{% block content %}
<section class="ftco-section">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 text-center mb-5">
                
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="wrapper">
                    <div class="row no-gutters mb-5">
                        <div class="col-md-3 " >
                            <div class="container">
                                <img class="displayed" src="../../static/theme/assets/img/protech-logo2.jpg" height="233px">
                            </div>
                            
                        </div>
                        <div class="col-md-6" style="display:flex; align-items:center">                            
                            <h6> 
                                Với kĩ thuật tiên tiến và hệ thống dây chuyền công nghệ sản xuất hàng đầu thế giới,  Công ty TNHH Thương mại Đại Phú - thành viên của Protech - Oxyplast Group cam kết mang đến cho khách hàng sản phẩm chất lượng đạt tiêu chuẩn ISO:9001-2015.
                                <br> <br>
                                Hướng tới sự hoàn hảo về cả chất lượng và thẩm mỹ, sản phẩm sơn bột Đại Phú đa dạng về màu sắc và thích hợp với nhiều bề mặt khác nhau, được tin dùng và sử dụng rộng rãi trên cả nước.
                            </h6>
                        </div>
                        <div class="col-md-3" >
                            <div class="container">
                                <img class="displayed" src="../../static/theme/assets/img/powder_coating.jpg" height="233px">
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page"><a href="{{ san_pham_url }}">Sản Phẩm</a></li>
      <li class="breadcrumb-item active" aria-current="page"><a href="{{ bot_son_url }}">Sơn Bột</a></li>
    </ol>
</nav>

<div class="container">
<div class="row">
    <div class="col-lg-6 col-sm-6 mb-4">
        <!-- Portfolio item 1-->
        <div class="card h-100 text-center">
            
            <img  src="../../static/theme/assets/img/indoor.jpg" height="370px" alt="..." />
    
                <div class="card-footer bg-gray text-white" style="font-size:18px">
                    <a class="text-decoration-none stretched-link" href="{{ trong_nha_url }}">
                        <div style="color: black">Trong Nhà</div> 
                    </a>
                </div>                  
        </div>
    </div>
    <div class="col-lg-6 col-sm-6 mb-4">
        <!-- Portfolio item 2-->
        <div class="card h-100 text-center">
            
            <img  src="../../static/theme/assets/img/outdoor.jpeg" height="370px" alt="..." />
    
                <div class="card-footer bg-gray text-white" style="font-size:18px">
                    <a class="text-decoration-none stretched-link" href="{{ ngoai_troi_url }}">
                        <div style="color: black">Ngoài Trời</div> 
                    </a>
                </div>                  
        </div>
    </div>
</div>
</div>

{% endblock %}

daiphu_website/templates/bot_son/ngoai_troi.html
{% extends 'base.html' %}
{% load static %}
{% block title %} 
Bột Sơn Ngoài Trời
{% endblock%}

{% block content %}

<!-- carousel slide-->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active" >
      <img class="d-block w-100 " src="../../static/theme/assets/img/equip_auto/auto1.jpg" alt="First slide">
    </div>
  </div>
</div>
<!--breadcrumb -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page"><a href="{{ san_pham_url }}">Sản Phẩm</a></li>
      <li class="breadcrumb-item active" aria-current="page"><a href="{{ bot_son_url }}">Bột Sơn</a></li>
      <li class="breadcrumb-item active" aria-current="page"><a href="{{ ngoai_troi_url }}">Bột Sơn Ngoài Trời</a></li>
    </ol>
</nav>

<!--content-->
<div class="row">
  <!-- item 1-->
  <div class="col-lg-3 col-sm-6 mb-4">
      <div class="card h-100 text-center gcard zoomIn animated">
          <img class="card-img-top" src="../../static/theme/assets/img/outdoor3.jpg" height="300px" alt="..." />
          <div class="card-body" >
            <h3 class="card-title text-red">Hệ Polyester-HAA</h3>
            <p>Dòng sản phẩm bột sơn sử dụng nhựa hệ Polyester-HAA</p>
          </div>
          <div class="card-footer text-white" style="font-size:18px;">
              <a class="text-decoration-none stretched-link" href="{{ he_polyester_haa_url }}">
                  <div style="color:black"><span class="fas fa-link"></span>&#9 Hệ Polyester-HAA</div>
              </a>
          </div>                  
      </div>
  </div>
  <!-- item 2-->
  <div class="col-lg-3 col-sm-6 mb-4">
    <div class="card h-100 text-center gcard zoomIn animated">
        <img class="card-img-top" src="../../static/theme/assets/img/outdoor2.jpg" height="300px" alt="..." />
        <div class="card-body" >
          <h3 class="card-title text-red">Hệ Polyester-TGIC</h3>
          <p>Dòng sản phẩm bột sơn sử dụng nhựa hệ Polyester-TGIC</p>
        </div>
        <div class="card-footer text-white" style="font-size:18px;">
            <a class="text-decoration-none stretched-link" href="{{ he_polyester_tgic_url }}">
                <div style="color:black"><span class="fas fa-link"></span>&#9 Hệ Polyester-TGIC</div>
            </a>
        </div>                  
    </div>
  </div>
  <!-- item 3-->
  <div class="col-lg-3 col-sm-6 mb-4">
    <div class="card h-100 text-center gcard zoomIn animated">
        <img class="card-img-top" src="../../static/theme/assets/img/nhom.jpg" height="300px" alt="..." />
        <div class="card-body" >
          <h3 class="card-title text-red">Hệ Polyester-Urithane</h3>
          <p>Dòng sản phẩm bột sơn sử dụng nhựa hệ Polyester-Urithane</p>
        </div>
        <div class="card-footer text-white" style="font-size:18px;">
            <a class="text-decoration-none stretched-link" href="{{ he_polyester_urethane_url }}">
                <div style="color:black"><span class="fas fa-link"></span>&#9 Hệ Polyester-Urithane</div>
            </a>
        </div>                  
    </div>
  </div>
</div>
{% endblock%}

daiphu_website/templates/bot_son/trong_nha.html
{% extends 'base.html' %}
{% load static %}
{% block title %} 
Bột Sơn Trong Nhà 
{% endblock%}


{% block content %}
<!-- carousel slide-->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active" >
      <img src="../../static/theme/assets/img/indoor.jpg" height="400px" width="100%" alt="First slide">
    </div>
    
  </div>
</div>
<!--breadcrumb -->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page"><a href="{{ san_pham_url }}">Sản Phẩm</a></li>
      <li class="breadcrumb-item active" aria-current="page"><a href="{{ bot_son_url }}">Bột Sơn</a></li>
      <li class="breadcrumb-item active" aria-current="page"><a href="{{ trong_nha_url }}">Bột Sơn Trong Nhà</a></li>
    </ol>
</nav>
<div class="row">
  <!-- item 1-->
  <div class="col-lg-3 col-sm-6 mb-4">
      <div class="card h-100 text-center gcard zoomIn animated">
          <img class="img-fluid3 card-img-top" src="../../static/theme/assets/img/den1.jpg" alt="..." />
          <div class="card-body" >
            <h3 class="card-title text-red">Hệ Epoxy</h3>
            <p>Dòng sản phẩm bột sơn sử dụng nhựa hệ Epoxy</p>
          </div>
          <div class="card-footer text-white" style="font-size:18px;">
              <a class="text-decoration-none stretched-link" href="{{ he_epoxy_url }}">
                  <div style="color:black"><span class="fas fa-link"></span>&#9 Hệ Epoxy</div>
              </a>
          </div>                  
      </div>
  </div>
  <!-- item 2-->
  <div class="col-lg-3 col-sm-6 mb-4">
    <div class="card h-100 text-center gcard zoomIn animated">
        <img class="img-fluid3 card-img-top" src="../../static/theme/assets/img/den4.jpg" alt="..." />
        <div class="card-body" >
          <h3 class="card-title text-red">Hệ Polyester Epoxy</h3>
          <p>Dòng sản phẩm bột sơn sử dụng nhựa hệ Polyester-Epoxy</p>
        </div>
        <div class="card-footer text-white" style="font-size:18px;">
            <a class="text-decoration-none stretched-link" href="{{ he_polyester_epoxy_url }}">
                <div style="color:black"><span class="fas fa-link"></span>&#9 Hệ Polyester Epoxy</div>
            </a>
        </div>                  
    </div>
  </div>
</div>
{% endblock %}